title: Microbial Diversity Lab
url: "https://sawlab.org"
baseurl: "/"

remote_theme: researcher

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://sawlab.org"
footer_text: "Home"

sass:
    style: compressed
    sass_dir: _sass
