title: Jimmy Saw    
url: "https://jimmysaw.github.io/"
baseurl: "/"

#remote_theme: researcher
remote_theme: gravity

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://jimmysaw.github.io/"
footer_text: "Home"

sass:
    style: compressed
    sass_dir: _sass
