title: Saw Microbial Diversity Lab
url: "//jimmysaw.github.io/"
baseurl: "/"

remote_theme: researcher

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "//jimmysaw.github.io/"
footer_text: "Home"

sass:
    style: compressed
    sass_dir: _sass
